### ISSUE TITLE
Produce species annotation result without counts

### ISSUE THREAD

**Issue by LujingF** [uhkniazi/HPRU_Metagenomics#1]
Hi, very appreciate your method. But, I couldn't find counts result when I use your MEGEN5 command-line. Have you ever came across this problems before? Further more, could you please give me a example of species annotation output? Thanks a lot.

**Comment by uhkniazi** [comment]
Hi, thank you for the message. This workflow was part of a diagnostic pipeline written for Public Health England (PHE) back in 2015 I think. I have not worked on this project for a while, so my answers are based on memory (you may need to do some current research).

I found that you can generate a command line file, by running megan 5 first in GUI mode. It should produce a set of commands in the megan terminal, which you can then copy and paste in a text file to produce a commands file (this allows you to use this command file in a script for batch processing for future samples). I assume you have named the input and output file names correctly, as my text snippets are just examples. 

I suggest run magan 5 in GUI mode and see if you get the count files output. 

The species annotation output should be a csv file with 2 columns, one with species names and the second with the abundance counts. See the gatAlpha function in megan_csv_import.R

hope this was helpful. good luck
